// ─── Mock Recent Activity Feed ────────────────────────────────────────────────
export const RECENT_ACTIVITY = [
  {
    id: 1,
    type: 'estimate_revised',
    description: 'Oracle Fusion ERP — estimate revised by Priya S.',
    time: '2h ago',
    color: '#34D399',
    colorLabel: 'green',
    icon: 'edit',
    roleTag: 'Estimator',
  },
  {
    id: 2,
    type: 'approved',
    description: 'Infrastructure Build Phase 2 — approved by Super User',
    time: '5h ago',
    color: '#00D4FF',
    colorLabel: 'cyan',
    icon: 'check',
    roleTag: 'Super User',
  },
  {
    id: 3,
    type: 'rate_card_updated',
    description: 'Rate card updated: Oracle Fusion Cloud — Unit SME',
    time: '1d ago',
    color: '#FFB347',
    colorLabel: 'amber',
    icon: 'database',
    roleTag: 'Unit SME',
  },
  {
    id: 4,
    type: 'calibration',
    description: 'Estimation engine recalibrated — 3 parameters adjusted',
    time: '2d ago',
    color: '#A78BFA',
    colorLabel: 'purple',
    icon: 'sliders',
    roleTag: 'Admin / COE',
  },
  {
    id: 5,
    type: 'new_estimate',
    description: 'Managed Services Q3 — new estimate created by Rahul K.',
    time: '3d ago',
    color: '#34D399',
    colorLabel: 'green',
    icon: 'plus',
    roleTag: 'Estimator',
  },
];
