// â”€â”€â”€ Knowledge Hub Mock Content â€” 81 items across 9 BUs Ã— 8 Types â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
// Types: guideline | template | data | pov | faq | casestudy | playbook | video

const now = new Date();
const daysAgo = (n) => new Date(now - n * 86400000).toISOString();

export const KNOWLEDGE_CONTENT = [

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ESU â€” Enterprise Solutions Unit (8 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'esu-g-001', title: 'Enterprise Software Estimation Guideline', subtitle: 'v3.0 â€” Enterprise Platforms',
    type: 'guideline', unitId: 'esu',
    description: 'Comprehensive guide for estimating large-scale enterprise software implementations including SAP, Oracle and Salesforce. Covers FIT-GAP analysis, configuration vs. customisation effort split and licence cost modelling.',
    fileType: 'pdf', fileSize: '3.8 MB', version: '3.0',
    owner: 'Rajesh K.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(5), updatedAt: daysAgo(5), downloadsCount: 89,
    tags: ['sap', 'oracle', 'salesforce', 'enterprise', 'fit-gap'],
    relatedIds: ['esu-t-001', 'esu-d-001'],
    evaInsight: 'This guideline is the starting point for any ESU estimation. Pair it with the ESU Project Template for a complete estimate package.',
  },
  {
    id: 'esu-t-001', title: 'ESU Project Estimation Template', subtitle: 'Covers SAP, Oracle & Salesforce',
    type: 'template', unitId: 'esu',
    description: 'Multi-sheet Excel template for enterprise platform estimations. Includes WBS, resource planning, licence cost, integration effort and governance overhead tabs.',
    fileType: 'xlsx', fileSize: '1.2 MB', version: '2.1',
    owner: 'Priya S.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(12), updatedAt: daysAgo(3), downloadsCount: 124,
    tags: ['template', 'excel', 'wbs', 'enterprise'],
    relatedIds: ['esu-g-001'],
    evaInsight: 'The most downloaded ESU asset. Use this template alongside the Enterprise Software Guideline for accurate platform estimates.',
  },
  {
    id: 'esu-d-001', title: 'ESU Historical Rate Data 2025', subtitle: 'Actuals from 2023â€“2025 Projects',
    type: 'data', unitId: 'esu',
    description: 'Anonymised historical effort and cost actuals from 34 ESU projects (2023â€“2025). Includes complexity segmentation, phase breakdowns and variance analysis against original estimates.',
    fileType: 'xlsx', fileSize: '890 KB', version: '2025.1',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(30), updatedAt: daysAgo(10), downloadsCount: 67,
    tags: ['historical', 'actuals', 'rate-data', 'variance'],
    relatedIds: ['esu-g-001'],
    evaInsight: 'Use this dataset for analogous estimation. Filter by project complexity tier to find comparable historical benchmarks.',
  },
  {
    id: 'esu-pov-001', title: 'Build vs Buy Decision Framework', subtitle: 'Strategic Estimation Perspective',
    type: 'pov', unitId: 'esu',
    description: 'Point of view paper exploring total cost of ownership considerations when evaluating build-from-scratch versus commercial platform procurement. Covers hidden costs, vendor risk and 5-year TCO model.',
    fileType: 'pdf', fileSize: '1.4 MB', version: '1.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(45), updatedAt: daysAgo(45), downloadsCount: 203,
    tags: ['tco', 'build-vs-buy', 'strategy', 'procurement'],
    relatedIds: ['esu-g-001', 'esu-cs-001'],
    evaInsight: 'Excellent pre-sales document. Often used during client discovery to frame TCO discussions before formal estimation begins.',
  },
  {
    id: 'esu-faq-001', title: 'ESU Estimation FAQs', subtitle: 'Top 25 Questions Answered',
    type: 'faq', unitId: 'esu',
    description: 'Curated answers to the 25 most common ESU estimation questions â€” covering licence costs, integration complexity scoring, change request delta estimation and approval thresholds.',
    fileType: 'pdf', fileSize: '620 KB', version: '1.3',
    owner: 'Priya S.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(60), updatedAt: daysAgo(15), downloadsCount: 178,
    tags: ['faq', 'guidance', 'quick-reference'],
    relatedIds: ['esu-g-001'],
    evaInsight: 'Quick reference for new estimators joining ESU projects. EVA can answer most of these questions directly â€” just ask!',
  },
  {
    id: 'esu-cs-001', title: 'SAP S/4HANA Greenfield Migration', subtitle: 'Case Study â€” Financial Services Client',
    type: 'casestudy', unitId: 'esu',
    description: '18-month SAP S/4HANA greenfield implementation for a Tier-1 bank. Documents the estimation approach used (bottom-up with parametric cross-check), key variance drivers and lessons learned.',
    fileType: 'pptx', fileSize: '4.2 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(90), updatedAt: daysAgo(90), downloadsCount: 312,
    tags: ['sap', 's4hana', 'migration', 'case-study', 'financial-services'],
    relatedIds: ['esu-g-001', 'esu-t-001'],
    evaInsight: 'One of the most referenced ESU case studies. The variance analysis section reveals common estimation pitfalls in greenfield SAP projects.',
  },
  {
    id: 'esu-pb-001', title: 'ESU Estimation Playbook', subtitle: 'Step-by-Step Estimation Guide for ESU',
    type: 'playbook', unitId: 'esu', chapterCount: 7,
    description: 'Comprehensive 7-chapter playbook covering the full ESU estimation lifecycle: from initial scope capture through methodology selection, template usage, stakeholder review and final submission.',
    fileType: 'pdf', fileSize: '5.1 MB', version: '2.0',
    owner: 'Rajesh K.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(40), updatedAt: daysAgo(8), downloadsCount: 95,
    tags: ['playbook', 'process', 'step-by-step', 'lifecycle'],
    relatedIds: ['esu-g-001', 'esu-t-001'],
    evaInsight: 'The definitive ESU estimator reference. Chapter 3 on FIT-GAP estimation is particularly valuable for Oracle implementations.',
  },
  {
    id: 'esu-v-001', title: 'Enterprise Estimation Walkthrough', subtitle: 'Training Video Â· 18:42',
    type: 'video', unitId: 'esu', videoDuration: '18:42',
    description: 'End-to-end video walkthrough of estimating a mid-size ERP implementation using Calibre. Covers template usage, methodology selection and the FIT-GAP analysis approach in real-time.',
    fileType: 'mp4', fileSize: '284 MB', version: '1.0',
    owner: 'Priya S.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(25), updatedAt: daysAgo(25), downloadsCount: 441,
    tags: ['training', 'erp', 'walkthrough', 'video'],
    relatedIds: ['esu-pb-001', 'esu-t-001'],
    evaInsight: 'Most-watched ESU asset. The section at 08:30 explaining FIT-GAP scoring is frequently cited by estimators.',
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ADM â€” Application Development & Maintenance (10 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'adm-g-001', title: 'Oracle Fusion ERP Estimation Guideline', subtitle: 'v2.1 â€” Oracle Fusion Specialist',
    type: 'guideline', unitId: 'adm',
    description: 'Comprehensive guide for estimating Oracle Fusion ERP implementations including HCM, Finance and SCM modules. Covers FIT-GAP methodology, configuration complexity scoring and integration effort.',
    fileType: 'pdf', fileSize: '2.4 MB', version: '2.1',
    owner: 'Priya S.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(10), updatedAt: daysAgo(2), downloadsCount: 47,
    tags: ['oracle', 'erp', 'fit-gap', 'estimation', 'parametric'],
    relatedIds: ['adm-t-001', 'itis-g-001'],
    evaInsight: 'Pairs well with the Parametric method. Use the FIT-GAP template alongside this guide for Oracle module estimations.',
  },
  {
    id: 'adm-g-002', title: 'Web Application Development Estimation Guide', subtitle: 'v1.5 â€” Agile & Waterfall',
    type: 'guideline', unitId: 'adm',
    description: 'Estimation guide for custom web application development covering both agile (story-point based) and waterfall (function-point based) approaches. Includes frontend, backend and API effort splits.',
    fileType: 'pdf', fileSize: '1.8 MB', version: '1.5',
    owner: 'Nathan B.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(20), updatedAt: daysAgo(7), downloadsCount: 83,
    tags: ['web', 'agile', 'waterfall', 'story-points', 'function-points'],
    relatedIds: ['adm-t-002', 'adm-pb-001'],
    evaInsight: 'For greenfield web apps, the Agile section with velocity-based estimation is most accurate when team size and sprint cadence are known.',
  },
  {
    id: 'adm-t-001', title: 'Oracle Fusion FIT-GAP Estimation Template', subtitle: 'HCM | Finance | SCM Modules',
    type: 'template', unitId: 'adm',
    description: 'Multi-module Excel template for Oracle Fusion FIT-GAP analysis. Separate tabs for HCM, Finance and SCM with auto-calculated complexity scores, effort estimates and configuration vs. customisation splits.',
    fileType: 'xlsx', fileSize: '2.1 MB', version: '3.0',
    owner: 'Priya S.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(15), updatedAt: daysAgo(3), downloadsCount: 156,
    tags: ['oracle', 'fit-gap', 'template', 'hcm', 'finance', 'scm'],
    relatedIds: ['adm-g-001'],
    evaInsight: 'Most downloaded ADM template. Load it with the Oracle Fusion Guideline for a complete estimation package.',
  },
  {
    id: 'adm-t-002', title: 'ADM Sprint-Based Estimation Template', subtitle: 'Agile Project Estimation',
    type: 'template', unitId: 'adm',
    description: 'Excel template for sprint-based agile project estimation. Includes velocity calculator, story-point to effort converter, team composition planner and release timeline projector.',
    fileType: 'xlsx', fileSize: '980 KB', version: '2.2',
    owner: 'Nathan B.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(18), updatedAt: daysAgo(5), downloadsCount: 98,
    tags: ['agile', 'sprint', 'velocity', 'story-points', 'template'],
    relatedIds: ['adm-g-002'],
    evaInsight: 'Set your team velocity baseline in tab 1 before filling other sheets â€” it drives all downstream calculations.',
  },
  {
    id: 'adm-d-001', title: 'ADM Historical Rate Card 2025', subtitle: 'Effort & Cost Actuals',
    type: 'data', unitId: 'adm',
    description: 'Anonymised rate card data from 52 ADM projects (2022â€“2025). Segmented by technology stack, project size, delivery model and geography. Includes variance analysis and outlier explanations.',
    fileType: 'xlsx', fileSize: '1.4 MB', version: '2025.1',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(28), updatedAt: daysAgo(8), downloadsCount: 71,
    tags: ['rate-card', 'historical', 'actuals', 'variance'],
    relatedIds: ['adm-g-001', 'adm-g-002'],
    evaInsight: 'Sort by Technology Stack column first â€” filtering to your specific tech reduces variance range by ~30%.',
  },
  {
    id: 'adm-pov-001', title: 'Agile vs Waterfall Estimation: The Real Trade-offs', subtitle: 'Point of View',
    type: 'pov', unitId: 'adm',
    description: 'Analysis of the accuracy implications of choosing agile story-point vs. waterfall function-point estimation methods. Draws on Calibre portfolio data to reveal when each approach outperforms the other.',
    fileType: 'pdf', fileSize: '1.1 MB', version: '1.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(55), updatedAt: daysAgo(55), downloadsCount: 189,
    tags: ['agile', 'waterfall', 'methodology', 'pov', 'accuracy'],
    relatedIds: ['adm-g-002'],
    evaInsight: 'Key takeaway: agile estimation has lower initial accuracy (Â±20%) but converges faster once 2 sprints of velocity data exist.',
  },
  {
    id: 'adm-faq-001', title: 'ADM Common Estimation Questions', subtitle: 'Top 30 FAQs for ADM Projects',
    type: 'faq', unitId: 'adm',
    description: 'Top 30 most asked ADM estimation questions covering scope definition, team sizing, defect effort allocation, UAT estimation, technical debt and change request handling.',
    fileType: 'pdf', fileSize: '730 KB', version: '1.2',
    owner: 'Nathan B.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(65), updatedAt: daysAgo(20), downloadsCount: 214,
    tags: ['faq', 'quick-reference', 'scope', 'change-requests'],
    relatedIds: ['adm-g-001', 'adm-g-002'],
    evaInsight: 'Questions 12â€“18 on UAT and defect effort allocation are the most frequently referenced by estimators.',
  },
  {
    id: 'adm-cs-001', title: 'E-Commerce Platform Migration Case Study', subtitle: 'Retail Client Â· 14-Month Delivery',
    type: 'casestudy', unitId: 'adm',
    description: 'End-to-end case study of a complex e-commerce platform migration from legacy to microservices architecture. Documents the bottom-up estimation methodology, accuracy achieved (Â±6%) and variance root causes.',
    fileType: 'pptx', fileSize: '3.6 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(100), updatedAt: daysAgo(100), downloadsCount: 267,
    tags: ['migration', 'microservices', 'e-commerce', 'case-study', 'retail'],
    relatedIds: ['adm-g-002', 'adm-t-002'],
    evaInsight: 'The section on API integration effort estimation (slide 18â€“22) is regularly referenced for similar migration scoping exercises.',
  },
  {
    id: 'adm-pb-001', title: 'ADM Estimation Playbook', subtitle: '8 Chapters Â· Full Lifecycle Guide',
    type: 'playbook', unitId: 'adm', chapterCount: 8,
    description: 'The definitive ADM estimation playbook covering all phases: requirements analysis, WBS creation, methodology selection, template usage, review cycles and submission. Includes agile and waterfall variants.',
    fileType: 'pdf', fileSize: '6.2 MB', version: '3.0',
    owner: 'Priya S.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(35), updatedAt: daysAgo(6), downloadsCount: 132,
    tags: ['playbook', 'lifecycle', 'agile', 'waterfall', 'wbs'],
    relatedIds: ['adm-g-001', 'adm-g-002', 'adm-t-001'],
    evaInsight: 'Start with Chapter 2 (Scope Decomposition) â€” the WBS structuring approach in this chapter is the foundation for all ADM estimates.',
  },
  {
    id: 'adm-v-001', title: 'ADM Methodology Walkthrough', subtitle: 'Training Video Â· 24:15',
    type: 'video', unitId: 'adm', videoDuration: '24:15',
    description: 'Live walkthrough covering Oracle Fusion FIT-GAP estimation from scratch: scope intake, FIT/GAP scoring, effort calculation and template completion. Demonstrates both guided and advanced modes in Calibre.',
    fileType: 'mp4', fileSize: '380 MB', version: '2.0',
    owner: 'Nathan B.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(22), updatedAt: daysAgo(22), downloadsCount: 523,
    tags: ['training', 'oracle', 'fit-gap', 'walkthrough', 'video'],
    relatedIds: ['adm-g-001', 'adm-t-001'],
    evaInsight: 'Most popular ADM video. The FIT-GAP scoring demo at 11:00 is the critical section for new estimators.',
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // ITIS â€” IT Infrastructure & Services (8 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'itis-g-001', title: 'Infrastructure Estimation Guideline', subtitle: 'v2.0 Â· Server, Network & Storage',
    type: 'guideline', unitId: 'itis',
    description: 'Comprehensive guide for estimating IT infrastructure engagements: server sizing, network design, storage planning, data centre operations and managed infrastructure services.',
    fileType: 'pdf', fileSize: '2.8 MB', version: '2.0',
    owner: 'Samira J.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(8), updatedAt: daysAgo(8), downloadsCount: 61,
    tags: ['infrastructure', 'server', 'network', 'storage', 'estimation'],
    relatedIds: ['itis-t-001', 'itis-d-001'],
    evaInsight: 'Section 4 on cloud vs on-premise cost modelling is essential reading before starting any infrastructure estimate.',
  },
  {
    id: 'itis-t-001', title: 'Server & Network Estimation Template', subtitle: 'Unit Rate Ã— Quantity Model',
    type: 'template', unitId: 'itis',
    description: 'Excel template using unit rate Ã— quantity models for server, network and storage estimation. Includes TCO calculator, refresh cycle planning and bandwidth sizing worksheets.',
    fileType: 'xlsx', fileSize: '1.6 MB', version: '2.3',
    owner: 'Samira J.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(14), updatedAt: daysAgo(4), downloadsCount: 88,
    tags: ['infrastructure', 'template', 'tco', 'server', 'network'],
    relatedIds: ['itis-g-001'],
    evaInsight: 'Enter your unit quantities in the Summary tab first â€” the model auto-populates all cost calculations from your rate library.',
  },
  {
    id: 'itis-d-001', title: 'ITIS Infrastructure Pricing Data 2025', subtitle: 'Market Rates & Benchmarks',
    type: 'data', unitId: 'itis',
    description: 'Current market pricing data for compute, storage, network and managed services. Segmented by vendor, geography, contract term and volume tiers. Updated quarterly.',
    fileType: 'xlsx', fileSize: '1.1 MB', version: 'Q1-2025',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(45), updatedAt: daysAgo(12), downloadsCount: 54,
    tags: ['pricing', 'market-rates', 'benchmarks', 'infrastructure'],
    relatedIds: ['itis-t-001'],
    evaInsight: 'Always use the latest quarterly version â€” infrastructure pricing has been shifting significantly with cloud vendor competition.',
  },
  {
    id: 'itis-pov-001', title: 'Cloud vs On-Premise: A 5-Year TCO Perspective', subtitle: 'Strategic Point of View',
    type: 'pov', unitId: 'itis',
    description: 'TCO comparison framework for cloud vs on-premise decision-making. Includes hidden cost analysis, exit risk, data sovereignty considerations and financial modelling approach.',
    fileType: 'pdf', fileSize: '1.7 MB', version: '2.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(70), updatedAt: daysAgo(70), downloadsCount: 276,
    tags: ['cloud', 'on-premise', 'tco', 'strategy', 'decision-framework'],
    relatedIds: ['itis-g-001', 'itis-d-001'],
    evaInsight: 'Top client-facing ITIS document. Use it in pre-sales to frame infrastructure investment discussions objectively.',
  },
  {
    id: 'itis-faq-001', title: 'ITIS Infrastructure Estimation FAQs', subtitle: '22 Questions Answered',
    type: 'faq', unitId: 'itis',
    description: 'Answers to the 22 most common infrastructure estimation questions: HA sizing, DR costs, managed service FTE ratios, upgrade cycles, software licensing and vendor support costs.',
    fileType: 'pdf', fileSize: '540 KB', version: '1.1',
    owner: 'Samira J.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(80), updatedAt: daysAgo(25), downloadsCount: 143,
    tags: ['faq', 'infrastructure', 'ha', 'dr', 'licensing'],
    relatedIds: ['itis-g-001'],
    evaInsight: 'The HA/DR cost allocation questions (Q8-Q12) are the most frequently referenced when estimating resilience requirements.',
  },
  {
    id: 'itis-cs-001', title: 'Data Centre Migration Case Study', subtitle: 'Manufacturing Client Â· Full DC Consolidation',
    type: 'casestudy', unitId: 'itis',
    description: 'Complete data centre consolidation project for a global manufacturer: 3 legacy DCs merged into 1 modern facility. Documents the estimation approach, accuracy (Â±9%) and migration phasing strategy.',
    fileType: 'pptx', fileSize: '5.1 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(110), updatedAt: daysAgo(110), downloadsCount: 198,
    tags: ['data-centre', 'migration', 'consolidation', 'case-study'],
    relatedIds: ['itis-g-001', 'itis-t-001'],
    evaInsight: 'The phased migration approach in slides 15-20 is a useful reference for any DC consolidation scope discussion.',
  },
  {
    id: 'itis-pb-001', title: 'ITIS Estimation Playbook', subtitle: '6 Chapters Â· Infrastructure Lifecycle',
    type: 'playbook', unitId: 'itis', chapterCount: 6,
    description: '6-chapter ITIS estimation playbook: scope capture, infrastructure sizing, unit rate application, TCO modelling, vendor validation and submission process.',
    fileType: 'pdf', fileSize: '4.4 MB', version: '1.5',
    owner: 'Samira J.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(50), updatedAt: daysAgo(9), downloadsCount: 77,
    tags: ['playbook', 'infrastructure', 'tco', 'sizing'],
    relatedIds: ['itis-g-001', 'itis-t-001'],
    evaInsight: 'Chapter 3 on unit rate application is critical â€” incorrect rate selection is the #1 cause of ITIS estimation variance.',
  },
  {
    id: 'itis-v-001', title: 'Infrastructure Estimation Training', subtitle: 'Training Video Â· 21:08',
    type: 'video', unitId: 'itis', videoDuration: '21:08',
    description: 'Practical training video demonstrating how to complete an infrastructure estimate using the ITIS template: server sizing, network bandwidth calculation, TCO modelling and pricing data application.',
    fileType: 'mp4', fileSize: '320 MB', version: '1.0',
    owner: 'Samira J.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(30), updatedAt: daysAgo(30), downloadsCount: 289,
    tags: ['training', 'infrastructure', 'sizing', 'tco', 'video'],
    relatedIds: ['itis-t-001', 'itis-pb-001'],
    evaInsight: 'The TCO modelling section (13:00-17:30) is the most rewatched segment â€” bookmark it for client demos.',
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // BPS â€” Business Process Services (8 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'bps-g-001', title: 'BPS Process Estimation Guideline', subtitle: 'v2.0 Â· FTE-Based Services',
    type: 'guideline', unitId: 'bps',
    description: 'Estimation guideline for FTE-based business process outsourcing engagements. Covers volume-based staffing models, SLA-driven cost structures, transition effort and ramp-up periods.',
    fileType: 'pdf', fileSize: '2.2 MB', version: '2.0',
    owner: 'Leila F.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(12), updatedAt: daysAgo(4), downloadsCount: 55,
    tags: ['bps', 'fte', 'outsourcing', 'sla', 'estimation'],
    relatedIds: ['bps-t-001', 'bps-d-001'],
    evaInsight: 'BPS estimates have the highest sensitivity to volume assumptions â€” use the sensitivity analysis tab in the template.',
  },
  {
    id: 'bps-t-001', title: 'FTE-Based Estimation Template', subtitle: 'BPS Staffing & Cost Model',
    type: 'template', unitId: 'bps',
    description: 'Comprehensive Excel model for FTE-based BPS estimation. Includes volume-to-FTE converter, role-grade cost ladder, attrition modelling, transition cost calculator and SLA penalty risk model.',
    fileType: 'xlsx', fileSize: '1.8 MB', version: '3.1',
    owner: 'Leila F.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(20), updatedAt: daysAgo(6), downloadsCount: 109,
    tags: ['fte', 'staffing', 'template', 'sla', 'attrition'],
    relatedIds: ['bps-g-001'],
    evaInsight: 'The attrition modelling tab is often underused but critically important for multi-year BPS engagements.',
  },
  {
    id: 'bps-d-001', title: 'BPS SLA Benchmark Data', subtitle: 'Industry Benchmarks 2024-2025',
    type: 'data', unitId: 'bps',
    description: 'Benchmarking data for BPS SLA achievement rates across process categories: Finance & Accounting, HR, Customer Operations and Supply Chain. Segmented by geography and engagement size.',
    fileType: 'xlsx', fileSize: '760 KB', version: '2025.1',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(35), updatedAt: daysAgo(15), downloadsCount: 42,
    tags: ['sla', 'benchmarks', 'bps', 'finance', 'hr', 'customer-ops'],
    relatedIds: ['bps-g-001', 'bps-t-001'],
    evaInsight: 'Cross-reference these SLA benchmarks with the client\'s required SLAs to identify risk areas before pricing.',
  },
  {
    id: 'bps-pov-001', title: 'Automation Impact on BPS Estimation', subtitle: 'RPA & AI in BPS Costing',
    type: 'pov', unitId: 'bps',
    description: 'Explores how RPA, AI and intelligent automation are changing FTE calculations in BPS engagements. Includes a framework for estimating automation uplift and the displacement-to-savings ratio.',
    fileType: 'pdf', fileSize: '1.3 MB', version: '1.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(60), updatedAt: daysAgo(60), downloadsCount: 234,
    tags: ['automation', 'rpa', 'ai', 'bps', 'fte', 'pov'],
    relatedIds: ['bps-g-001', 'ai-g-001'],
    evaInsight: 'Critical reading for any BPS estimate where client is considering automation â€” it changes the FTE model significantly.',
  },
  {
    id: 'bps-faq-001', title: 'BPS Estimation FAQs', subtitle: '20 Common Questions',
    type: 'faq', unitId: 'bps',
    description: 'Answers to the 20 most common BPS estimation questions: FTE calculation methodology, transition costs, steady-state modelling, volume variability buffers and SLA penalty structures.',
    fileType: 'pdf', fileSize: '490 KB', version: '1.0',
    owner: 'Leila F.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(75), updatedAt: daysAgo(30), downloadsCount: 127,
    tags: ['faq', 'bps', 'fte', 'transition', 'sla'],
    relatedIds: ['bps-g-001'],
    evaInsight: 'Q5 on volume variability buffers is the most critical for contract negotiations â€” it directly impacts pricing risk.',
  },
  {
    id: 'bps-cs-001', title: 'Finance Process Outsourcing Case Study', subtitle: 'Global Pharma Client Â· AP/AR Transition',
    type: 'casestudy', unitId: 'bps',
    description: 'End-to-end case study of a Finance & Accounting BPO transition for a global pharmaceutical company. Covers the estimation methodology, transition phasing, SLA achievement and year-1 variance analysis.',
    fileType: 'pptx', fileSize: '3.8 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(95), updatedAt: daysAgo(95), downloadsCount: 176,
    tags: ['bpo', 'finance', 'ap-ar', 'pharma', 'case-study'],
    relatedIds: ['bps-g-001', 'bps-t-001'],
    evaInsight: 'The transition phasing model in this case study (slides 12-16) is frequently adapted for new BPS engagement proposals.',
  },
  {
    id: 'bps-pb-001', title: 'BPS Estimation Playbook', subtitle: '5 Chapters Â· BPS Deal Lifecycle',
    type: 'playbook', unitId: 'bps', chapterCount: 5,
    description: '5-chapter playbook for BPS estimation from RFP response through contract signature: scope capture, FTE modelling, transition planning, SLA structuring and commercial modelling.',
    fileType: 'pdf', fileSize: '3.9 MB', version: '1.5',
    owner: 'Leila F.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(42), updatedAt: daysAgo(7), downloadsCount: 64,
    tags: ['playbook', 'bps', 'deal-lifecycle', 'fte', 'commercial'],
    relatedIds: ['bps-g-001', 'bps-t-001'],
    evaInsight: 'Chapter 4 on SLA structuring is invaluable â€” getting SLAs wrong at the estimation stage is the primary BPS commercial risk.',
  },
  {
    id: 'bps-v-001', title: 'BPS Process Estimation Training', subtitle: 'Training Video Â· 19:55',
    type: 'video', unitId: 'bps', videoDuration: '19:55',
    description: 'Practical training video on BPS estimation fundamentals: volume to FTE conversion, transition cost modelling, SLA risk assessment and template walkthrough for a Finance & Accounting scope.',
    fileType: 'mp4', fileSize: '298 MB', version: '1.0',
    owner: 'Leila F.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(28), updatedAt: daysAgo(28), downloadsCount: 318,
    tags: ['training', 'bps', 'fte', 'sla', 'video'],
    relatedIds: ['bps-t-001', 'bps-pb-001'],
    evaInsight: 'The FTE-to-volume conversion demo at 06:20 is the key technique new estimators need to understand first.',
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // TI â€” Technology Integration (8 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'ti-g-001', title: 'Integration Estimation Guideline', subtitle: 'v1.5 Â· API, Middleware & iPaaS',
    type: 'guideline', unitId: 'ti',
    description: 'Estimation guide for system integration projects covering API development, middleware configuration, iPaaS (MuleSoft, Boomi) and point-to-point integration. Includes complexity scoring model.',
    fileType: 'pdf', fileSize: '2.0 MB', version: '1.5',
    owner: 'Chen W.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(9), updatedAt: daysAgo(3), downloadsCount: 49,
    tags: ['integration', 'api', 'middleware', 'mulesoft', 'boomi', 'ipaas'],
    relatedIds: ['ti-t-001', 'adm-g-001'],
    evaInsight: 'The integration complexity scoring model in Section 3 is the most important tool â€” it drives all downstream effort estimates.',
  },
  {
    id: 'ti-t-001', title: 'API Integration Estimation Template', subtitle: 'Complexity Ã— Volume Model',
    type: 'template', unitId: 'ti',
    description: 'Excel template for API and integration estimation using a complexity Ã— volume model. Includes interface inventory, complexity scoring, effort hours calculator and phasing planner.',
    fileType: 'xlsx', fileSize: '1.3 MB', version: '2.0',
    owner: 'Chen W.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(16), updatedAt: daysAgo(5), downloadsCount: 76,
    tags: ['api', 'integration', 'template', 'complexity', 'interface-inventory'],
    relatedIds: ['ti-g-001'],
    evaInsight: 'Complete the Interface Inventory tab first â€” it\'s the foundation that all other calculations depend on.',
  },
  {
    id: 'ti-d-001', title: 'Integration Complexity Scoring Data', subtitle: 'Effort Benchmarks by Integration Type',
    type: 'data', unitId: 'ti',
    description: 'Benchmarking data for integration effort by type (REST, SOAP, batch, streaming) and complexity (simple/medium/complex). Derived from 28 TI projects (2023â€“2025).',
    fileType: 'xlsx', fileSize: '640 KB', version: '2025.1',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(40), updatedAt: daysAgo(12), downloadsCount: 38,
    tags: ['integration', 'complexity', 'benchmarks', 'effort-data'],
    relatedIds: ['ti-t-001'],
    evaInsight: 'Use the REST/Simple row as your baseline and apply the complexity multipliers to adjust for more complex integrations.',
  },
  {
    id: 'ti-pov-001', title: 'Middleware vs Direct Integration: The Estimation Impact', subtitle: 'Point of View',
    type: 'pov', unitId: 'ti',
    description: 'Analysis of the cost and effort implications of choosing middleware/iPaaS versus direct point-to-point integration. Includes long-term maintenance cost modelling and scalability considerations.',
    fileType: 'pdf', fileSize: '1.0 MB', version: '1.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(58), updatedAt: daysAgo(58), downloadsCount: 167,
    tags: ['middleware', 'ipaas', 'pov', 'integration', 'tco'],
    relatedIds: ['ti-g-001'],
    evaInsight: 'Useful for client conversations where they\'re debating integration architecture â€” the 5-year cost comparison on page 8 is compelling.',
  },
  {
    id: 'ti-faq-001', title: 'TI Integration Estimation FAQs', subtitle: '18 Questions Answered',
    type: 'faq', unitId: 'ti',
    description: 'Answers to 18 common TI estimation questions: interface count discovery, complexity classification, error handling effort, testing overhead, performance testing and iPaaS licence estimation.',
    fileType: 'pdf', fileSize: '480 KB', version: '1.0',
    owner: 'Chen W.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(72), updatedAt: daysAgo(28), downloadsCount: 118,
    tags: ['faq', 'integration', 'complexity', 'testing'],
    relatedIds: ['ti-g-001'],
    evaInsight: 'Q7 on error handling effort is frequently underestimated â€” the 15-20% overhead noted there is consistent across projects.',
  },
  {
    id: 'ti-cs-001', title: 'ERP-CRM Integration Case Study', subtitle: 'SAP to Salesforce Â· Global Retailer',
    type: 'casestudy', unitId: 'ti',
    description: 'Real-time bidirectional integration between SAP S/4HANA and Salesforce CRM for a global retailer. Documents the integration estimation approach, 47-interface scope and accuracy achieved (Â±7%).',
    fileType: 'pptx', fileSize: '4.0 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(88), updatedAt: daysAgo(88), downloadsCount: 221,
    tags: ['sap', 'salesforce', 'crm', 'erp', 'integration', 'case-study'],
    relatedIds: ['ti-g-001', 'ti-t-001'],
    evaInsight: 'The interface complexity breakdown in this case study (slide 9) is an excellent reference for similar ERP-CRM scope discussions.',
  },
  {
    id: 'ti-pb-001', title: 'TI Estimation Playbook', subtitle: '5 Chapters Â· Integration Project Lifecycle',
    type: 'playbook', unitId: 'ti', chapterCount: 5,
    description: 'TI playbook covering the full integration estimation lifecycle: interface discovery, complexity scoring, middleware selection, effort calculation and phased delivery planning.',
    fileType: 'pdf', fileSize: '3.6 MB', version: '1.0',
    owner: 'Chen W.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(48), updatedAt: daysAgo(10), downloadsCount: 59,
    tags: ['playbook', 'integration', 'interface-inventory', 'complexity'],
    relatedIds: ['ti-g-001', 'ti-t-001'],
    evaInsight: 'Chapter 2 on Interface Discovery is the most valuable â€” it prevents scope creep by ensuring all integrations are identified upfront.',
  },
  {
    id: 'ti-v-001', title: 'Integration Estimation Training Video', subtitle: 'Training Video Â· 16:33',
    type: 'video', unitId: 'ti', videoDuration: '16:33',
    description: 'Practical training on TI estimation: how to build an interface inventory, score complexity, apply effort benchmarks and complete the API estimation template for a real integration scope.',
    fileType: 'mp4', fileSize: '248 MB', version: '1.0',
    owner: 'Chen W.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(26), updatedAt: daysAgo(26), downloadsCount: 264,
    tags: ['training', 'integration', 'api', 'complexity', 'video'],
    relatedIds: ['ti-t-001', 'ti-pb-001'],
    evaInsight: 'The complexity scoring walkthrough (09:00-13:00) is especially valuable â€” it removes the subjectivity from integration sizing.',
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // Cyber Security (9 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'cyber-g-001', title: 'Cybersecurity Assessment Estimation Guideline', subtitle: 'v2.0 Â· Full Security Portfolio',
    type: 'guideline', unitId: 'cyber',
    description: 'End-to-end guide for estimating cybersecurity engagements including maturity assessments, security architecture, SOC setup, vulnerability management and compliance programmes.',
    fileType: 'pdf', fileSize: '3.1 MB', version: '2.0',
    owner: 'Fatima A.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(7), updatedAt: daysAgo(7), downloadsCount: 72,
    tags: ['cybersecurity', 'assessment', 'soc', 'compliance', 'estimation'],
    relatedIds: ['cyber-t-001', 'cyber-d-001'],
    evaInsight: 'Security estimation requires a maturity baseline before effort can be quantified â€” Section 2 explains how to establish this.',
  },
  {
    id: 'cyber-g-002', title: 'Penetration Testing Estimation Guideline', subtitle: 'v1.2 Â· Pen Test Scoping',
    type: 'guideline', unitId: 'cyber',
    description: 'Specific guideline for scoping and estimating penetration testing engagements: external/internal pen tests, web application testing, red team exercises and social engineering assessments.',
    fileType: 'pdf', fileSize: '1.5 MB', version: '1.2',
    owner: 'Fatima A.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(18), updatedAt: daysAgo(6), downloadsCount: 53,
    tags: ['penetration-testing', 'red-team', 'web-app-security', 'scoping'],
    relatedIds: ['cyber-t-001'],
    evaInsight: 'The asset scope multiplier table in Appendix B is the primary tool for pen test scoping â€” use it to translate asset count to effort days.',
  },
  {
    id: 'cyber-t-001', title: 'Security Implementation Estimation Template', subtitle: 'Multi-Domain Security Template',
    type: 'template', unitId: 'cyber',
    description: 'Comprehensive Excel template covering all major cybersecurity domains: identity & access, network security, endpoint protection, SIEM/SOC, data protection and compliance frameworks.',
    fileType: 'xlsx', fileSize: '2.2 MB', version: '2.0',
    owner: 'Fatima A.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(22), updatedAt: daysAgo(7), downloadsCount: 91,
    tags: ['template', 'cybersecurity', 'iam', 'siem', 'soc', 'compliance'],
    relatedIds: ['cyber-g-001'],
    evaInsight: 'Use the Domain Selector tab to activate only the relevant security domains for your scope â€” it hides unused worksheets automatically.',
  },
  {
    id: 'cyber-d-001', title: 'Cyber Security Benchmark Data 2025', subtitle: 'Effort & Cost by Security Domain',
    type: 'data', unitId: 'cyber',
    description: 'Effort and cost benchmarks for cybersecurity implementations across 12 security domains. Derived from 31 client engagements (2023â€“2025). Segmented by industry sector and organisation size.',
    fileType: 'xlsx', fileSize: '980 KB', version: '2025.1',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(42), updatedAt: daysAgo(14), downloadsCount: 48,
    tags: ['cybersecurity', 'benchmarks', 'effort-data', 'cost-data'],
    relatedIds: ['cyber-g-001'],
    evaInsight: 'Filter by industry sector before using these benchmarks â€” security maturity baselines vary significantly across industries.',
  },
  {
    id: 'cyber-pov-001', title: 'Zero Trust Architecture: What It Really Costs', subtitle: 'Point of View',
    type: 'pov', unitId: 'cyber',
    description: 'Realistic cost estimation framework for Zero Trust Architecture (ZTA) adoption. Deconstructs the hype and provides a phased investment model based on maturity stages and technology selection.',
    fileType: 'pdf', fileSize: '1.6 MB', version: '1.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(65), updatedAt: daysAgo(65), downloadsCount: 312,
    tags: ['zero-trust', 'zta', 'architecture', 'pov', 'investment'],
    relatedIds: ['cyber-g-001'],
    evaInsight: 'The phased ZTA investment model on pages 10-14 is extremely useful for setting client expectations on Zero Trust timelines and costs.',
  },
  {
    id: 'cyber-faq-001', title: 'Cyber Security Estimation FAQs', subtitle: '24 Questions Answered',
    type: 'faq', unitId: 'cyber',
    description: '24 common cybersecurity estimation questions: maturity assessment effort, SOC FTE sizing, tool licensing costs, compliance gap remediation and incident response capability estimation.',
    fileType: 'pdf', fileSize: '600 KB', version: '1.1',
    owner: 'Fatima A.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(78), updatedAt: daysAgo(22), downloadsCount: 161,
    tags: ['faq', 'cybersecurity', 'soc', 'compliance', 'licensing'],
    relatedIds: ['cyber-g-001'],
    evaInsight: 'Q9 on SOC FTE sizing and Q17 on compliance gap remediation effort are the most frequently referenced questions.',
  },
  {
    id: 'cyber-cs-001', title: 'SOC Implementation Case Study', subtitle: 'Financial Services Client Â· 24/7 SOC',
    type: 'casestudy', unitId: 'cyber',
    description: 'Full SIEM-based 24/7 SOC implementation for a Tier-2 bank: 6-month build, 18-month managed service. Documents estimation methodology, technology selection, FTE modelling and Year 1 accuracy.',
    fileType: 'pptx', fileSize: '4.5 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(105), updatedAt: daysAgo(105), downloadsCount: 287,
    tags: ['soc', 'siem', 'financial-services', 'managed-security', 'case-study'],
    relatedIds: ['cyber-g-001', 'cyber-t-001'],
    evaInsight: 'The SIEM use-case effort breakdown (slide 14) and the SOC FTE ramp model (slide 18) are the key reference sections.',
  },
  {
    id: 'cyber-pb-001', title: 'Cyber Security Estimation Playbook', subtitle: '7 Chapters Â· Security Programme Lifecycle',
    type: 'playbook', unitId: 'cyber', chapterCount: 7,
    description: '7-chapter playbook covering the full cybersecurity estimation lifecycle: maturity assessment, gap analysis, architecture design, implementation estimation, managed service modelling and compliance costing.',
    fileType: 'pdf', fileSize: '5.8 MB', version: '2.0',
    owner: 'Fatima A.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(44), updatedAt: daysAgo(11), downloadsCount: 83,
    tags: ['playbook', 'cybersecurity', 'maturity', 'gap-analysis', 'compliance'],
    relatedIds: ['cyber-g-001', 'cyber-t-001'],
    evaInsight: 'Chapter 2 (Maturity Assessment Estimation) is the critical starting point â€” without a baseline, all downstream security effort estimates are unreliable.',
  },
  {
    id: 'cyber-v-001', title: 'Security Estimation Training', subtitle: 'Training Video Â· 22:40',
    type: 'video', unitId: 'cyber', videoDuration: '22:40',
    description: 'Comprehensive training covering cybersecurity estimation techniques: maturity assessment scoping, security domain effort modelling and SOC FTE calculation using the Cyber Security template.',
    fileType: 'mp4', fileSize: '338 MB', version: '1.0',
    owner: 'Fatima A.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(32), updatedAt: daysAgo(32), downloadsCount: 356,
    tags: ['training', 'cybersecurity', 'maturity', 'soc', 'video'],
    relatedIds: ['cyber-t-001', 'cyber-pb-001'],
    evaInsight: 'The SOC FTE calculation demo at 15:00-19:00 is the section estimators rewatch most â€” it covers the shift rotation model in detail.',
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // AI â€” Artificial Intelligence Practice (11 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'ai-g-001', title: 'AI/ML Project Estimation Guideline', subtitle: 'v2.5 Â· Machine Learning Lifecycle',
    type: 'guideline', unitId: 'ai',
    description: 'Estimation guideline for AI/ML projects covering the full data science lifecycle: data preparation, model development, training, validation, deployment and MLOps. Includes effort uncertainty modelling.',
    fileType: 'pdf', fileSize: '3.4 MB', version: '2.5',
    owner: 'Kavya N.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(6), updatedAt: daysAgo(2), downloadsCount: 94,
    tags: ['ai', 'ml', 'machine-learning', 'mlops', 'data-science'],
    relatedIds: ['ai-t-001', 'ai-d-001'],
    evaInsight: 'AI estimation has higher inherent uncertainty than other domains â€” Section 5 on effort uncertainty ranges is essential reading.',
  },
  {
    id: 'ai-g-002', title: 'GenAI Implementation Estimation Guide', subtitle: 'v1.0 Â· LLMs & Agentic Systems',
    type: 'guideline', unitId: 'ai',
    description: 'Estimation guide specifically for Generative AI implementations: LLM fine-tuning, RAG architecture, agentic systems, prompt engineering, evaluation frameworks and production deployment.',
    fileType: 'pdf', fileSize: '2.6 MB', version: '1.0',
    owner: 'Kavya N.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(4), updatedAt: daysAgo(1), downloadsCount: 187,
    tags: ['genai', 'llm', 'rag', 'agents', 'prompt-engineering', 'new'],
    relatedIds: ['ai-t-002', 'ai-pov-002'],
    evaInsight: 'Our newest guideline â€” GenAI estimation is still evolving. This guide captures the most current best practices from live engagements.',
  },
  {
    id: 'ai-t-001', title: 'AI Model Development Estimation Template', subtitle: 'ML Lifecycle Estimation',
    type: 'template', unitId: 'ai',
    description: 'Phased Excel template for AI/ML project estimation: data readiness assessment, feature engineering, model development iterations, testing, deployment and monitoring setup costs.',
    fileType: 'xlsx', fileSize: '1.7 MB', version: '2.0',
    owner: 'Kavya N.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(14), updatedAt: daysAgo(4), downloadsCount: 118,
    tags: ['ai', 'ml', 'template', 'model-development', 'mlops'],
    relatedIds: ['ai-g-001'],
    evaInsight: 'The Data Readiness Assessment tab is the most critical â€” poor data quality is the #1 cause of AI project budget overruns.',
  },
  {
    id: 'ai-t-002', title: 'LLM & RAG Implementation Template', subtitle: 'GenAI Project Cost Model',
    type: 'template', unitId: 'ai',
    description: 'Cost and effort template for LLM-based implementations: base model selection, fine-tuning compute costs, RAG architecture build, vector database sizing, evaluation and production hosting.',
    fileType: 'xlsx', fileSize: '1.4 MB', version: '1.0',
    owner: 'Kavya N.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(5), updatedAt: daysAgo(1), downloadsCount: 143,
    tags: ['llm', 'rag', 'genai', 'template', 'compute-cost', 'new'],
    relatedIds: ['ai-g-002'],
    evaInsight: 'The Compute Cost Calculator tab requires API pricing inputs â€” use current OpenAI/Azure AI pricing from their respective pricing pages.',
  },
  {
    id: 'ai-d-001', title: 'AI Project Historical Data 2024-2025', subtitle: 'ML Effort Actuals',
    type: 'data', unitId: 'ai',
    description: 'Effort and cost actuals from 24 AI/ML projects (2024â€“2025). Segmented by project type, model complexity, data volume and team composition. Includes data preparation effort ratios.',
    fileType: 'xlsx', fileSize: '820 KB', version: '2025.1',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(38), updatedAt: daysAgo(11), downloadsCount: 66,
    tags: ['ai', 'historical-data', 'actuals', 'ml', 'effort-ratios'],
    relatedIds: ['ai-g-001'],
    evaInsight: 'The data prep to total effort ratio column is the most-used benchmark â€” industry average is 60-80% for data prep in ML projects.',
  },
  {
    id: 'ai-pov-001', title: 'AI Estimation: Why Traditional Methods Fall Short', subtitle: 'Point of View',
    type: 'pov', unitId: 'ai',
    description: 'Analysis of why traditional software estimation techniques underperform for AI/ML projects and what adaptations are needed. Proposes an iterative estimation model for AI projects.',
    fileType: 'pdf', fileSize: '1.2 MB', version: '1.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(62), updatedAt: daysAgo(62), downloadsCount: 298,
    tags: ['ai', 'estimation-methodology', 'pov', 'ml', 'iterative'],
    relatedIds: ['ai-g-001'],
    evaInsight: 'Set client expectations early using this paper â€” AI projects have inherent uncertainty that traditional fixed-price models struggle to accommodate.',
  },
  {
    id: 'ai-pov-002', title: 'GenAI Cost Estimation: The Hidden Factors', subtitle: 'New Point of View Â· 2025',
    type: 'pov', unitId: 'ai',
    description: 'Explores the frequently overlooked cost drivers in GenAI implementations: prompt engineering iteration, evaluation infrastructure, guardrails, hallucination monitoring and model drift management.',
    fileType: 'pdf', fileSize: '1.1 MB', version: '1.0',
    owner: 'Kavya N.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(3), updatedAt: daysAgo(3), downloadsCount: 221,
    tags: ['genai', 'llm', 'hidden-costs', 'pov', 'evaluation', 'new'],
    relatedIds: ['ai-g-002', 'ai-t-002'],
    evaInsight: 'The evaluation infrastructure cost section (pages 6-9) is surprising to most clients â€” budget 20-30% extra for ongoing model evaluation.',
  },
  {
    id: 'ai-faq-001', title: 'AI Project Estimation FAQs', subtitle: '28 Questions Answered',
    type: 'faq', unitId: 'ai',
    description: 'Top 28 AI/ML estimation questions: data readiness scoring, model iteration budgeting, GPU compute estimation, MLOps toolchain costs, GenAI vs custom ML selection and team skill mix.',
    fileType: 'pdf', fileSize: '710 KB', version: '1.2',
    owner: 'Kavya N.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(50), updatedAt: daysAgo(18), downloadsCount: 243,
    tags: ['faq', 'ai', 'ml', 'genai', 'compute', 'data-readiness'],
    relatedIds: ['ai-g-001', 'ai-g-002'],
    evaInsight: 'Q3 on data readiness scoring and Q19 on GenAI vs custom ML selection are the foundational questions to answer before estimating.',
  },
  {
    id: 'ai-cs-001', title: 'Predictive Analytics Platform Case Study', subtitle: 'Retail Client Â· Demand Forecasting ML',
    type: 'casestudy', unitId: 'ai',
    description: 'ML-based demand forecasting platform for a global retailer: 8-month implementation, 95%+ forecast accuracy achieved. Documents the bottom-up estimation approach and variance against actuals.',
    fileType: 'pptx', fileSize: '4.8 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(92), updatedAt: daysAgo(92), downloadsCount: 334,
    tags: ['ml', 'predictive-analytics', 'retail', 'forecasting', 'case-study'],
    relatedIds: ['ai-g-001', 'ai-t-001'],
    evaInsight: 'The data preparation effort breakdown in slides 11-14 is the most referenced section â€” data engineering was 68% of total effort in this project.',
  },
  {
    id: 'ai-pb-001', title: 'AI Estimation Playbook', subtitle: '9 Chapters Â· Full AI Lifecycle',
    type: 'playbook', unitId: 'ai', chapterCount: 9,
    description: 'The most comprehensive AI estimation playbook: 9 chapters covering data strategy, model selection, effort uncertainty, compute budgeting, GenAI costing, ethics overhead and MLOps planning.',
    fileType: 'pdf', fileSize: '7.2 MB', version: '1.0',
    owner: 'Kavya N.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(38), updatedAt: daysAgo(9), downloadsCount: 112,
    tags: ['playbook', 'ai', 'ml', 'genai', 'mlops', 'lifecycle'],
    relatedIds: ['ai-g-001', 'ai-g-002'],
    evaInsight: 'Chapter 5 on effort uncertainty modelling and Chapter 7 on GenAI compute budgeting are the newest and most practically useful chapters.',
  },
  {
    id: 'ai-v-001', title: 'AI Estimation Methodology Training', subtitle: 'Training Video Â· 31:22',
    type: 'video', unitId: 'ai', videoDuration: '31:22',
    description: 'The definitive AI estimation training video covering ML and GenAI estimation techniques, template walkthroughs, data readiness assessment and real-world effort calibration examples.',
    fileType: 'mp4', fileSize: '472 MB', version: '1.0',
    owner: 'Kavya N.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(20), updatedAt: daysAgo(20), downloadsCount: 612,
    tags: ['training', 'ai', 'ml', 'genai', 'methodology', 'video'],
    relatedIds: ['ai-pb-001', 'ai-t-001', 'ai-t-002'],
    evaInsight: 'Our longest and most comprehensive training video. The GenAI estimation section starting at 18:00 is brand new and covers LLM cost modelling.',
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // Data & Cloud (11 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'dc-g-001', title: 'Cloud Migration Estimation Guideline', subtitle: 'v3.0 Â· AWS, Azure & GCP',
    type: 'guideline', unitId: 'datacloud',
    description: 'Comprehensive guide for cloud migration estimation covering lift-and-shift, re-platform and re-architect approaches across AWS, Azure and GCP. Includes assessment, migration and cutover effort models.',
    fileType: 'pdf', fileSize: '4.1 MB', version: '3.0',
    owner: 'Yash P.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(8), updatedAt: daysAgo(1), downloadsCount: 108,
    tags: ['cloud', 'migration', 'aws', 'azure', 'gcp', 'lift-and-shift'],
    relatedIds: ['dc-t-001', 'dc-d-001'],
    evaInsight: 'The migration approach selection matrix in Section 3 (6R framework) should be the first thing completed â€” it drives all downstream cost estimates.',
  },
  {
    id: 'dc-g-002', title: 'Data Platform Estimation Guide', subtitle: 'v1.5 Â· Data Engineering & Analytics',
    type: 'guideline', unitId: 'datacloud',
    description: 'Estimation guide for data platform projects: data lake/warehouse design, ETL/ELT pipeline development, data governance, data quality engineering and analytics/BI layer implementation.',
    fileType: 'pdf', fileSize: '2.9 MB', version: '1.5',
    owner: 'Yash P.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(15), updatedAt: daysAgo(5), downloadsCount: 74,
    tags: ['data-platform', 'data-warehouse', 'etl', 'analytics', 'data-lake'],
    relatedIds: ['dc-t-002', 'dc-d-002'],
    evaInsight: 'Data volume and source system complexity are the two biggest effort drivers â€” quantify these precisely before estimating.',
  },
  {
    id: 'dc-t-001', title: 'Cloud TCO Estimation Template', subtitle: 'Multi-Cloud Financial Model',
    type: 'template', unitId: 'datacloud',
    description: 'Comprehensive multi-cloud TCO model with compute, storage, networking, managed services, support tiers, reserved instance optimisation and 3-year cost projection with sensitivity analysis.',
    fileType: 'xlsx', fileSize: '2.4 MB', version: '4.0',
    owner: 'Yash P.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(11), updatedAt: daysAgo(3), downloadsCount: 198,
    tags: ['cloud', 'tco', 'template', 'aws', 'azure', 'reserved-instances'],
    relatedIds: ['dc-g-001'],
    evaInsight: 'The most downloaded Data & Cloud asset. Enable Reserved Instance optimisation in Tab 3 to reduce TCO by 30-40% for stable workloads.',
  },
  {
    id: 'dc-t-002', title: 'Data Warehouse Estimation Template', subtitle: 'Snowflake Â· Databricks Â· Synapse',
    type: 'template', unitId: 'datacloud',
    description: 'Effort and cost template for modern data warehouse implementations on Snowflake, Databricks or Azure Synapse. Covers ingestion, transformation, semantic layer and consumption costs.',
    fileType: 'xlsx', fileSize: '1.9 MB', version: '2.1',
    owner: 'Yash P.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(19), updatedAt: daysAgo(6), downloadsCount: 122,
    tags: ['data-warehouse', 'snowflake', 'databricks', 'synapse', 'template'],
    relatedIds: ['dc-g-002'],
    evaInsight: 'Select your target platform in the Config tab first â€” it activates the correct pricing model for Snowflake, Databricks or Synapse.',
  },
  {
    id: 'dc-d-001', title: 'Cloud Pricing Benchmark Data 2025', subtitle: 'AWS, Azure & GCP Pricing',
    type: 'data', unitId: 'datacloud',
    description: 'Current cloud pricing benchmarks across AWS, Azure and GCP for compute (VMs/containers), storage, networking, managed databases and AI/ML services. Updated monthly. Includes reserved vs on-demand comparison.',
    fileType: 'xlsx', fileSize: '1.8 MB', version: 'July-2025',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(18), updatedAt: daysAgo(1), downloadsCount: 177,
    tags: ['cloud-pricing', 'aws', 'azure', 'gcp', 'benchmarks', 'compute'],
    relatedIds: ['dc-t-001'],
    evaInsight: 'Use the July 2025 version â€” cloud pricing changes monthly and older versions can significantly underestimate costs.',
  },
  {
    id: 'dc-d-002', title: 'Data Platform Historical Metrics', subtitle: 'Effort & Cost Actuals 2023-2025',
    type: 'data', unitId: 'datacloud',
    description: 'Effort and cost actuals from 19 data platform projects. Segmented by platform type, data volume tier, source count and team size. Includes pipeline development effort ratios.',
    fileType: 'xlsx', fileSize: '940 KB', version: '2025.1',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(36), updatedAt: daysAgo(13), downloadsCount: 58,
    tags: ['data-platform', 'historical-data', 'actuals', 'pipeline', 'effort'],
    relatedIds: ['dc-g-002'],
    evaInsight: 'The source-to-pipeline effort ratio data is particularly useful â€” projects consistently underestimate ingestion complexity.',
  },
  {
    id: 'dc-pov-001', title: 'Multi-Cloud Strategy: The Estimation Complexity', subtitle: 'Point of View',
    type: 'pov', unitId: 'datacloud',
    description: 'Analysis of how multi-cloud strategies increase estimation complexity: management overhead, networking costs, skill fragmentation and the hidden costs of cloud-native portability.',
    fileType: 'pdf', fileSize: '1.3 MB', version: '1.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(58), updatedAt: daysAgo(58), downloadsCount: 256,
    tags: ['multi-cloud', 'strategy', 'pov', 'complexity', 'management-overhead'],
    relatedIds: ['dc-g-001'],
    evaInsight: 'Use this when clients propose multi-cloud to set realistic expectations â€” the management overhead is typically 25-35% of the total cloud cost.',
  },
  {
    id: 'dc-faq-001', title: 'Data & Cloud Estimation FAQs', subtitle: '26 Questions Answered',
    type: 'faq', unitId: 'datacloud',
    description: 'Top 26 Data & Cloud estimation questions: migration approach selection, lift-and-shift vs re-architecture cost comparison, data egress cost estimation, reserved instance optimisation and FinOps setup.',
    fileType: 'pdf', fileSize: '660 KB', version: '1.2',
    owner: 'Yash P.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(68), updatedAt: daysAgo(22), downloadsCount: 189,
    tags: ['faq', 'cloud', 'migration', 'finops', 'reserved-instances'],
    relatedIds: ['dc-g-001', 'dc-g-002'],
    evaInsight: 'Q8 on data egress cost estimation is the most overlooked â€” networking costs can represent 15-25% of cloud spend and are often excluded from initial estimates.',
  },
  {
    id: 'dc-cs-001', title: 'AWS Cloud Migration Case Study', subtitle: 'Manufacturing Client Â· 200 Workload Migration',
    type: 'casestudy', unitId: 'datacloud',
    description: '200-workload cloud migration to AWS for a global manufacturer. Mixed migration approach (lift-and-shift + re-platform). Documents estimation methodology, accuracy achieved (Â±11%) and post-migration optimisation.',
    fileType: 'pptx', fileSize: '5.4 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(98), updatedAt: daysAgo(98), downloadsCount: 378,
    tags: ['aws', 'migration', 'manufacturing', 'workloads', 'case-study'],
    relatedIds: ['dc-g-001', 'dc-t-001'],
    evaInsight: 'The workload discovery to migration effort ratio in this case study (slide 8) is the most referenced benchmark for large-scale migrations.',
  },
  {
    id: 'dc-pb-001', title: 'Cloud Estimation Playbook', subtitle: '8 Chapters Â· Cloud Migration Lifecycle',
    type: 'playbook', unitId: 'datacloud', chapterCount: 8,
    description: '8-chapter cloud estimation playbook: discovery, assessment, migration strategy, effort modelling, TCO analysis, risk adjustment, FinOps planning and submission process.',
    fileType: 'pdf', fileSize: '6.8 MB', version: '2.0',
    owner: 'Yash P.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(36), updatedAt: daysAgo(8), downloadsCount: 141,
    tags: ['playbook', 'cloud', 'migration', 'tco', 'finops'],
    relatedIds: ['dc-g-001', 'dc-t-001'],
    evaInsight: 'Chapter 4 on effort modelling and Chapter 6 on risk adjustment are the highest-value sections for estimators new to cloud projects.',
  },
  {
    id: 'dc-v-001', title: 'Cloud Migration Estimation Training', subtitle: 'Training Video Â· 27:45',
    type: 'video', unitId: 'datacloud', videoDuration: '27:45',
    description: 'End-to-end training on cloud migration estimation: application assessment, migration strategy selection, TCO modelling, effort calculation and risk factor application â€” using the Cloud TCO Template.',
    fileType: 'mp4', fileSize: '416 MB', version: '1.0',
    owner: 'Yash P.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(24), updatedAt: daysAgo(24), downloadsCount: 487,
    tags: ['training', 'cloud', 'migration', 'tco', 'video'],
    relatedIds: ['dc-t-001', 'dc-pb-001'],
    evaInsight: 'The TCO template walkthrough (12:00-20:00) is the most valuable section â€” it covers the reserved instance optimisation that most estimators miss.',
  },

  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  // IAE â€” Integrated Application Engineering (8 items)
  // â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
  {
    id: 'iae-g-001', title: 'IAE Estimation Guideline', subtitle: 'v1.5 Â· Application Re-Engineering',
    type: 'guideline', unitId: 'iae',
    description: 'Estimation guide for integrated application engineering: legacy assessment, modernisation approach selection, low-code/no-code estimation, API-first architecture and composable application design.',
    fileType: 'pdf', fileSize: '2.5 MB', version: '1.5',
    owner: 'Zara M.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(11), updatedAt: daysAgo(4), downloadsCount: 43,
    tags: ['iae', 'modernisation', 'legacy', 'low-code', 'composable'],
    relatedIds: ['iae-t-001', 'iae-d-001'],
    evaInsight: 'The modernisation approach selection matrix in Section 2 (7R framework) is the critical tool â€” choosing the wrong approach invalidates the entire estimate.',
  },
  {
    id: 'iae-t-001', title: 'Application Engineering Estimation Template', subtitle: 'Modernisation & Low-Code Model',
    type: 'template', unitId: 'iae',
    description: 'Excel template for IAE estimation covering legacy assessment, modernisation effort by approach (rehost/refactor/rebuild), low-code platform effort modelling and API development costs.',
    fileType: 'xlsx', fileSize: '1.5 MB', version: '1.3',
    owner: 'Zara M.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(17), updatedAt: daysAgo(5), downloadsCount: 68,
    tags: ['iae', 'template', 'modernisation', 'low-code', 'legacy-assessment'],
    relatedIds: ['iae-g-001'],
    evaInsight: 'Complete the Legacy Complexity Assessment tab first â€” it feeds the modernisation effort multipliers in all other worksheets.',
  },
  {
    id: 'iae-d-001', title: 'IAE Historical Rate Data', subtitle: 'Effort Actuals 2023-2025',
    type: 'data', unitId: 'iae',
    description: 'Effort and cost actuals from 18 IAE projects (2023â€“2025). Segmented by modernisation approach, legacy complexity tier, application size and target architecture. Includes variance analysis.',
    fileType: 'xlsx', fileSize: '720 KB', version: '2025.1',
    owner: 'Anika R.', ownerRole: 'Admin / COE', department: 'both',
    uploadedAt: daysAgo(43), updatedAt: daysAgo(14), downloadsCount: 36,
    tags: ['iae', 'historical-data', 'actuals', 'modernisation', 'effort'],
    relatedIds: ['iae-g-001'],
    evaInsight: 'Sort by Modernisation Approach first â€” rebuild projects consistently run 2.5x the effort of rehost projects for the same application size.',
  },
  {
    id: 'iae-pov-001', title: 'Modern Application Architecture: Cost Realities', subtitle: 'Point of View',
    type: 'pov', unitId: 'iae',
    description: 'Explores the real total costs of modern application architectures: microservices, event-driven and composable. Challenges common assumptions about cost savings versus monolithic approaches.',
    fileType: 'pdf', fileSize: '1.2 MB', version: '1.0',
    owner: 'Marcus T.', ownerRole: 'Unit SME', department: 'sales',
    uploadedAt: daysAgo(62), updatedAt: daysAgo(62), downloadsCount: 201,
    tags: ['microservices', 'composable', 'architecture', 'pov', 'tco'],
    relatedIds: ['iae-g-001'],
    evaInsight: 'Excellent pre-sales POV for architecture discussions. The microservices operational complexity cost data on page 11 challenges many client assumptions.',
  },
  {
    id: 'iae-faq-001', title: 'IAE Estimation FAQs', subtitle: '22 Questions Answered',
    type: 'faq', unitId: 'iae',
    description: '22 IAE estimation questions: legacy assessment effort, modernisation approach ROI, low-code platform selection, API design effort, testing overhead for modernised applications and technical debt handling.',
    fileType: 'pdf', fileSize: '560 KB', version: '1.0',
    owner: 'Zara M.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(76), updatedAt: daysAgo(26), downloadsCount: 129,
    tags: ['faq', 'iae', 'legacy', 'modernisation', 'low-code', 'api'],
    relatedIds: ['iae-g-001'],
    evaInsight: 'Q4 on technical debt quantification is the trickiest IAE estimation challenge â€” the scoring matrix in that answer is particularly useful.',
  },
  {
    id: 'iae-cs-001', title: 'Legacy Modernisation Case Study', subtitle: 'Insurance Client Â· COBOL to Cloud-Native',
    type: 'casestudy', unitId: 'iae',
    description: 'COBOL legacy system modernisation to cloud-native microservices for a leading insurer. Documents the phased estimation approach, complexity assessment methodology and accuracy achieved (Â±8%).',
    fileType: 'pptx', fileSize: '4.2 MB', version: '1.0',
    owner: 'David L.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(102), updatedAt: daysAgo(102), downloadsCount: 243,
    tags: ['legacy', 'cobol', 'modernisation', 'insurance', 'microservices', 'case-study'],
    relatedIds: ['iae-g-001', 'iae-t-001'],
    evaInsight: 'The COBOL complexity assessment model in slides 7-11 is widely reused for similar mainframe modernisation scoping exercises.',
  },
  {
    id: 'iae-pb-001', title: 'IAE Estimation Playbook', subtitle: '6 Chapters Â· Modernisation Lifecycle',
    type: 'playbook', unitId: 'iae', chapterCount: 6,
    description: '6-chapter IAE playbook: legacy assessment, approach selection, effort modelling, low-code estimation, phased delivery planning and risk quantification for application modernisation projects.',
    fileType: 'pdf', fileSize: '4.6 MB', version: '1.0',
    owner: 'Zara M.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(46), updatedAt: daysAgo(10), downloadsCount: 72,
    tags: ['playbook', 'iae', 'modernisation', 'legacy-assessment', 'lifecycle'],
    relatedIds: ['iae-g-001', 'iae-t-001'],
    evaInsight: 'Chapter 2 (Approach Selection) is where most IAE estimates go wrong â€” read this chapter before touching any estimation template.',
  },
  {
    id: 'iae-v-001', title: 'IAE Estimation Training', subtitle: 'Training Video Â· 20:18',
    type: 'video', unitId: 'iae', videoDuration: '20:18',
    description: 'Practical training on IAE estimation: legacy complexity scoring, modernisation approach selection, effort calculation using the IAE template and risk factor application for application re-engineering projects.',
    fileType: 'mp4', fileSize: '304 MB', version: '1.0',
    owner: 'Zara M.', ownerRole: 'Unit SME', department: 'both',
    uploadedAt: daysAgo(27), updatedAt: daysAgo(27), downloadsCount: 298,
    tags: ['training', 'iae', 'legacy', 'modernisation', 'video'],
    relatedIds: ['iae-t-001', 'iae-pb-001'],
    evaInsight: 'The legacy complexity scoring demo at 07:00-12:00 is the critical section â€” it eliminates the subjectivity from legacy application assessment.',
  },
];

// â”€â”€ Helper functions â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export function getContentByUnit(unitId) {
  if (!unitId || unitId === 'all') return KNOWLEDGE_CONTENT;
  return KNOWLEDGE_CONTENT.filter((c) => c.unitId === unitId);
}

export function getContentByType(type) {
  if (!type || type === 'all') return KNOWLEDGE_CONTENT;
  return KNOWLEDGE_CONTENT.filter((c) => c.type === type);
}

export function getContentById(id) {
  return KNOWLEDGE_CONTENT.find((c) => c.id === id) || null;
}

export function getRelatedContent(item) {
  if (!item?.relatedIds?.length) return [];
  return item.relatedIds.map(getContentById).filter(Boolean);
}

export function getUnitStats(unitId) {
  const items = getContentByUnit(unitId);
  const newThisWeek = items.filter((c) => {
    const days = (Date.now() - new Date(c.updatedAt)) / 86400000;
    return days <= 7;
  }).length;
  const byType = {};
  items.forEach((c) => { byType[c.type] = (byType[c.type] || 0) + 1; });
  return { total: items.length, newThisWeek, byType };
}

export function searchContent(query) {
  if (!query?.trim()) return KNOWLEDGE_CONTENT;
  const q = query.toLowerCase();
  return KNOWLEDGE_CONTENT.filter(
    (c) =>
      c.title.toLowerCase().includes(q) ||
      c.description.toLowerCase().includes(q) ||
      c.tags.some((t) => t.includes(q)) ||
      c.owner.toLowerCase().includes(q) ||
      c.unitId.toLowerCase().includes(q)
  );
}



